import 'package:get/get.dart';

class MyTranslation extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        "ar": {
          "1": "اختر اللغة",
          "2": "التوريدات العموميه",
          "3":
              "ستجد كل ما تبحث عنه ضمن تطبيقنا المتواضع. نوفر لك كل ما سيحتاجه مصنعك أو شركتك أو حتى نشاطك التجاري،\n بما في ذلك منتجات السلامة المهنية ومكافحة الحرائق وغيرها.",
          "4": "عروض وخصومات",
          "5":
              "سوف يعجبك الامر لانك سوف تحصل علي خصومات وعروض لن تجدها الا لدينا نحن فقط",
          "o2": "اسرع خدمه توصيل",
          "o3":
              "تسليم موثوق وسريع وامن\n نقوم بتسليم منتجاتك بأسرع طريقة ممكنة",
          "8": "متابعه",
          "9": "تسجيل الدخول",
          "10": "مرحبا بعودتك",
          "o10": "الباسورد",
          "11":
              "يمكنك تسجيل الدخول من خلال البريد وكلمة المرور او من خلال وسائل التواصل الاجتماعي",
          "12": "ادخل البريد الالكتروني",
          "o12": "الايميل ",
          "oo12": "ادخل الايميل ",
          "13": "ادخل كلمة المرور",
          "o13": "ادخل الباسورد",
          "14": "هل نسيت كلمة المرور",
          "o14": "اعادة كتابة الباسورد",
          "15": "تسجيل الدخول",
          "16": "ليس لديك حساب ? ",
          "17": "انشاء حساب",
          "18": "البريد الالكتروني",
          "19": "كلمة المرور",
          "20": "اسم المستخدم",
          "o20": "مرحبا بك في صفحة انشاء الحسابات ",
          "o21":
              "في هذه الصفحة، يمكنك إنشاء حساب عن طريق ملء الحقول أدناه\n أو باستخدام وسائل التواصل الاجتماعي.\n إذا كان لديك حساب، يمكنك تسجيل الدخول مباشرة.",
          "21": "رقم الهاتف",
          "22": "ادخل رقم الهاتف",
          "23": "ادخل اسم المستخدم",
          "24":
              "انشاء حساب من خلال البريد وكلمة المرور او من خلال وسائل التواصل الاجتماعي",
          "25": " لديك حساب ? ",
          "26": "تسجيل الدخول",
          "27": "فحص البريد الالكتروني",
          "28": "تم انشاء الحساب بنجاح",
          "29": "الرجاء ادخال البريد لتلقي رمز التحقق",
          "30": "فحص",
          "31": "الذهاب لتسجيل الدخول",
          "32": "نجاح",
          "33": "حفظ",
          "34": "الرجاء ادخال كلمة المرور الجديدة",
          "35": "الكلمة الجديدة",
          "36": "تم اعادة تعيين كلمة المرور بنجاح",
          "37": "تهانينا",
          "38": "تم التسجيل بنجاح",
          "39": "الاسم غير صالح",
          "40": "الايميل غير صالح",
          "41": "رقم الهاتف غير صالح",
          "42": "المحتوي قصير",
          "43": "المحتوي كبير جدا ",
          "44": "لا يمكن أن تكون فارغة",
          "45": "هل نسيت كلمة المرور",
          "46": "اعادة تعيين الباسورد",
          "47": "حفظ",
          "48": "ادخل باسورد جديد",
          "49": "خد نايبك صبر",
          "50": "عاش ياوحش",
          "51": " جرب تاني ",
          "52": " السيستم بعافية  ",
          "53": "اطلع عند مدام حنان الدور التاني",
          "54": "روح اشحن وتعالي",
          "55": "الاقسام",
          "56": "المنتجات الاكثر مبيعاً",
          "57": "الخصومات",
        },
        "en": {
          "1": "Choose Language",
          "2": "Public supplies",
          "3":
              "You will find everything you are looking for within our humble application.\n We provide you with everything your factory, company, or even business will need,\n including occupational safety, fire-fighting, and other products.",
          "4": "Offers and discounts",
          "5":
              "You will like it because you will get discounts and offers that you will only find with us.",
          "o2": "Fast Delivery",
          "o3":
              "Reliable and Fast Deeilvery \n We Delivery Your Product the \n Fastest way Possible",
          "8": "Continue",
          "9": "Sign In",
          "10": "Welcome Back",
          "11":
              "Sign In Your Email And Password Or  Continue With Social Media",
          "12": "Enter Your Email",
          "o12": "Email",
          "oo12": "Enter your Email",
          "13": "Enter Your Password",
          "14": "Forget Password",
          "o14": "Enter Re password",
          "15": "Sign In",
          "16": "Dont Have An Account ? ",
          "17": "Sign Up",
          "19": "Password",
          "20": "Username",
          "21": "Phone",
          "o20": "Welcome to the account creation page",
          "o21":
              "On this page, you can create an account by filling out the fields below or\n using social media. If you have an account,\n you can log in directly.",
          "22": "Enter Your Phone",
          "23": "Enter Your Username",
          "24":
              "Sign Up With Your Email And Password OR Continue With Social Media",
          "25": " have an account ? ",
          "26": "SignIn",
          "27": "Check Email",
          "28": "Account successfully created",
          "29": "please Enter Your Email Address To Recive A verification code",
          "30": "check",
          "31": "Go To Login",
          "32": "Success",
          "33": "save",
          "34": "Please Enter new Password",
          "35": "New Password",
          "36": "Password has been reset successfully",
          "37": "congratulations",
          "38": "successfully registered",
          "39": "not valid username",
          "40": "not valid email",
          "41": "not valid phone",
          "42": "can't be less than",
          "43": "can't be more than",
          "44": "can't be Empty",
          "45": "Forgetpassword",
          "46": "ResetPassword",
          "47": "save",
          "48": "Enter New Password",
          "49": "loading...",
          "50": "",
          "51": "failure!",
          "52": "serverfailure!",
          "53": "",
          "54": "offlinefailure",
          "55": "Categories",
          "56": "Product for you",
          "57": "Offer",
          "": "",
        }
      };
}
